# Generated by Django 4.0.6 on 2022-07-21 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea',
            field=models.CharField(max_length=50),
        ),
    ]
