# Generated by Django 4.0.6 on 2022-07-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCRUD', '0002_tarea_descripcion_tarea_fecha_alter_tarea_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha',
            field=models.DateField(),
        ),
    ]
