# Generated by Django 4.0.6 on 2022-07-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCRUD', '0003_alter_tarea_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha',
        ),
    ]
